name: Metrics

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches: ['master', 'main']

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      # Checkout repo to allow commits
      - name: Checkout repository
        uses: actions/checkout@v3

      # Metrics base
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

      # ISO Calendar
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: alfredochavez
          filename: metrics-isocalendar.svg
          base: ''
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

      # Languages
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: alfredochavez
          filename: metrics-languages.svg
          base: ''
          plugin_languages: yes
          plugin_languages_details: percentage

      # Starred Topics
      - uses: lowlighter/metrics@latest
        with:
          token: NOT_NEEDED
          filename: metrics.plugin.topics.icons.svg
          base: ''
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
